version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: apps/webhook-relay-server/Dockerfile
      args:
        - "APP=webhook-relay-server"
    ports:
      - "3000:3000"
      - "9000:9000"
    environment:
      - "REDIS_URL=redis://redis:6379"
    depends_on:
      - redis
  client:
    build:
      context: .
      dockerfile: apps/webhook-relay-client/Dockerfile
      args:
        - "APP=webhook-relay-client"
    environment:
      - "SOURCE_URL=http://server:3000/webhooks/test/"
      - "TARGET_BASE_URL=http://integration-tests:3001"
    depends_on:
      - server
  integration-tests:
    build:
      context: .
      dockerfile: apps/integration-tests/Dockerfile
      args:
        - "APP=e2e"
    environment:
      - "WEBHOOK_RELAY_SERVER_BASE_URL=http://server:3000"
    ports:
      - "3001:3001"
    depends_on:
      - server
      - client
      - redis
  redis:
    image: redis
