apiVersion: apps/v1
kind: Deployment
metadata:
 name: webhook-relay-client
spec:
 selector:
   matchLabels:
     app: webhook-relay-client
 replicas: 1
 template:
   metadata:
     labels:
       app: webhook-relay-client
   spec:
     containers:
       - name: webhook-relay-client
         image: quay.io/codefresh/webhook-relay-client:1.0.9
         env:
           - name: SOURCE_URL
             value: "https://public-cluster-ingress-host/webhooks/csdp-runtime1/"
           - name: TARGET_BASE_URL
             value: "https://private-cluster-ingress-host"
