apiVersion: apps/v1
kind: Deployment
metadata:
 name: webhook-relay-client
spec:
 selector:
   matchLabels:
     app: webhook-relay-client
 replicas: 1
 template:
   metadata:
     labels:
       app: webhook-relay-client
   spec:
     containers:
       - name: webhook-relay-client
         image: danielcf/webhook-relay-client:test1
         imagePullPolicy: Never
         env:
           - name: SOURCE_URL
             value: "https://9183-87-68-200-96.ngrok.io/webhooks/prod-cf1/"
           - name: TARGET_BASE_URL
             value: "http://172.23.0.2"
